import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from './providers'
import {SidebarWithLogo} from "@/components/Sidebar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'CISO Next',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <head>
          <meta charSet="utf-8" />
          <meta name="description" content="Cyber Warden" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <title>Cyber Warden</title>
        </head>
        <Providers>
          <SidebarWithLogo />
          {children}
        </Providers>
      </body>
    </html>
  )
}
