import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {NavbarWithMegaMenu} from '@/components/Navbar'
import {FooterWithLogo} from "@/components/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'CISO Next',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`inter.className bg-gradient-to-t from-blue-gray-50 to-blue-gray-600`}>
        <NavbarWithMegaMenu />
        {children}
        <FooterWithLogo/>
      </body>
    </html>
  )
}
