import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {NavbarWithMegaMenu} from '@/components/Navbar'
import {FooterWithLogo} from "@/components/Footer";
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'CISO Next',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-screen bg-site bg-no-repeat bg-cover overflow-auto relative`}>

          <NavbarWithMegaMenu />
          {children}
          <div className='h-[4000px]'></div>
          {/* <FooterWithLogo/> */}
      </body>
    </html>
  )
}
